# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!
  INSTALL_DIR: ${PWD}

includes:
  os: "{{ .INSTALL_DIR }}/os"
  docker: "{{ .INSTALL_DIR }}/docker"
  dc: "{{ .INSTALL_DIR }}/docker-compose"
  ssl: "{{ .INSTALL_DIR }}/ssl"

tasks:
  default:
    cmds:
      - task -a
    silent: true
