version: '3'

tasks:
  update:
    desc: Updates your system packages and remove the old ones
    cmds:
      - sudo apt-get update
      - sudo apt-get upgrade -y
      - sudo apt-get dist-upgrade -y 
      - sudo apt-get autoclean -y 
      - sudo apt-get autoremove -y 
      - sudo apt-get clean -y
